name: Deploy to S3

on:
  workflow_dispatch:  # This enables manual trigger from the GitHub UI

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner for this job

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI for deployment
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Add AWS credentials in GitHub Secrets
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ap-south-1  # Set to your region

      # Step 3: Install dependencies from install_dependencies script
      - name: Install dependencies
        run: |
          chmod +x ./scripts/install_dependencies
          ./scripts/install_dependencies

      # Step 4: Build the application (if needed)
      - name: Build app
        run: |
          # This step can include the commands to build your app (e.g., copying files, compiling, etc.)
          echo "Building the app..."
          # Example: build your app or prepare the folder to upload to S3
          cp -r ./* /home/ubuntu/app_build

      # Step 5: Upload to S3
      - name: Deploy to S3
        run: |
          aws s3 sync /home/ubuntu/app_build s3://testcode01/ --delete

      # Step 6: Optional - Start the server if needed
      - name: Start server
        run: |
          chmod +x ./scripts/start_server
          ./scripts/start_server

      # Step 7: Optional - Stop the server if needed after deployment
      - name: Stop server
        run: |
          chmod +x ./scripts/stop_server
          ./scripts/stop_server
